"""Adicionando valor_pago e lote

Revision ID: 4efa4f50b43c
Revises: fbfd85a66944
Create Date: 2026-02-19 15:10:51.126810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4efa4f50b43c'
down_revision = 'fbfd85a66944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_pago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lote', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compareceu', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['telefone'])
        batch_op.drop_column('data_inscricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inscricao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('compareceu')
        batch_op.drop_column('lote')
        batch_op.drop_column('valor_pago')

    # ### end Alembic commands ###
